name: Build cmark

on: workflow_dispatch

defaults:
  run: 
    shell: bash

jobs:
  linux_window_build:
    runs-on: ubuntu-latest
    steps:

    - name: Make apt sources.list use the default Ubuntu repositories
      run: |
        curl https://raw.githubusercontent.com/godotengine/godot/master/misc/ci/sources.list > sources.list
        sudo cp -f sources.list /etc/apt/sources.list
        sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential mingw-w64
        
    - name: Clone cmark
      uses: actions/checkout@v2
      with:
        repository: commonmark/cmark
        path: cmark

    - name: Compile binaries
      run: |
        cd cmark
        mkdir build
        cd build
        cmake ..
        make
        cd ../
        make mingw
        cp build/src/libcmark.so.0.29.0 ../libcmark.so
        cb build-mingw/src/libcmark.dll ../libcmark.dll
     
    - name: Upload the Linux library
      uses: actions/upload-artifact@master
      with:
        name: libcmark.so
        path: libcmark.so

    - name: Upload the Windows library
      uses: actions/upload-artifact@master
      with:
        name: libcmark.dll
        path: libcmark.dll
 
  osx_build:
    runs-on: macos-latest

    steps:
    - name: Clone cmark
      uses: actions/checkout@v2
      with:
        repository: commonmark/cmark
        path: cmark

    - name: Compile binaries
      run: |
        cd cmark
        mkdir build
        cd build
        cmake ..
        make
        ls -al src
        cp src/libcmark.0.29.0.dylib ../../libcmark.dylib
    
    - name: Upload the library
      uses: actions/upload-artifact@master
      with:
        name: libcmark.dylib
        path: libcmark.dylib
