name: Debug

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, used for the release name'
        default: '0.0'
        required: true

jobs:
  greet:
    runs-on: windows-latest

    steps:
    
      - name: Test some windows commands
        run: |
          mkdir -p stuff && exit 0
          mkdir -p stuff && exit 0
          rm -rf stuff && exit 0
          rm -rf stuff2 && exit 0
          
