name: Debug

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, used for the release name'
        default: '0.0'
        required: true

jobs:
  greet:
    runs-on: windows-latest

    steps:
    
      - name: Test some windows commands
        run: |
          md dir1
          del dir1
          if exists dir1 del dir1
          md dir1
          md dir2
          md dir3
          move dir3 dir99
