name: Export MacOS Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, used for the release name'
        default: '0.0'
        required: true

defaults:
  run:
    shell: bash

jobs:
  macos_export:
    name: Export MacOS version
    runs-on: macos-latest
    
    steps:

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version
          
      - name: Clone the editor binaries
        uses: actions/checkout@v2
        with:
          repository: HungryProton/concept_graph_environment
          path: builds
      
      - name: Clone the ConceptGraph repository
        uses: actions/checkout@v2
        with:
          repository: HungryProton/concept_graph
          path: concept_graph
          ref: standalone
          submodules: recursive

      - name: Compile GDnative libraries
        run: |
          cd concept_graph/src/native/
          ./compile_all.sh osx
          
      - name: Check status
        run: |
          pwd
          echo "-- OSX Builds"
          ls -al builds/osx
          echo "-- Compiled gdnative"
          ls -al concept_graph/src/native/thirdparty/mesh_optimizer/bin/
          echo "-- Export presets"
          more concept_graph/export_presets.cfg
      
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: OSX Release ${{ github.event.inputs.version }}
            body: ''
            draft: true
            prerelease: true
      
      - name: Upload OSX lib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: concept_graph/src/native/thirdparty/mesh_optimizer/bin/osx/libmeshoptimizer.dylib
          asset_name: libmeshoptimizer.dylib
          asset_content_type: application/zip

      - name: Export the project
        run: |
          mkdir -p ConceptGraph
          builds/osx/godot.osx.opt.tools.64 --path concept_graph --export "osx" "../ConceptGraph/ConceptGraph"
          zip -r ConceptGraph-${{ github.event.inputs.version }}-osx.zip ConceptGraph

      - name: Upload OSX build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ConceptGraph-${{ github.event.inputs.version }}-osx.zip
          asset_name: ConceptGraph-osx.zip
          asset_content_type: application/zip
