name: Export Linux Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, used for the release name'
        default: '0.0'
        required: true

jobs:
  linux_export:
    name: Export Linux version
    runs-on: ubuntu-20.04
    
    steps:
        # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          curl https://raw.githubusercontent.com/godotengine/godot/master/misc/ci/sources.list > sources.list
          sudo cp -f sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Clone the ConceptGraph repository
        uses: actions/checkout@v2
        with:
          repository: HungryProton/concept_graph
          path: concept_graph
          ref: standalone
          submodules: recursive

      - name: Clone the editor binaries
        uses: actions/checkout@v2
        with:
          repository: HungryProton/concept_graph_environment
          path: builds

      - name: Compile GDnative libraries
        run: |
          cd concept_graph/src/native/
          ./compile_all.sh linux
          ./compile_all.sh windows

      - name: Export the project
        run: |
          mkdir -p ConceptGraph-linux
          mkdir -p ConceptGraph-windows
          
          builds/server/godot_server.x11.opt.tools.64 --path concept_graph --export "linux" "../ConceptGraph-linux/ConceptGraph"
          builds/server/godot_server.x11.opt.tools.64 --path concept_graph --export "windows" "../ConceptGraph-windows/ConceptGraph"          
          
          zip -r ConceptGraph-${{ github.event.inputs.version }}-linux.zip ConceptGraph-linux
          zip -r ConceptGraph-${{ github.event.inputs.version }}-windows.zip ConceptGraph-windows

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Linux Release ${{ github.event.inputs.version }}
            body: ''
            draft: true
            prerelease: true

      - name: Upload Linux build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ConceptGraph-${{ github.event.inputs.version }}-linux.zip
          asset_name: ConceptGraph for Linux
          asset_content_type: application/zip

      - name: Upload Windows build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ConceptGraph-${{ github.event.inputs.version }}-windows.zip
          asset_name: ConceptGraph for Linux
          asset_content_type: application/zip

